package tigo.com.bo.proxyondemand;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-09-14T18:19:39.660-04:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://bo.com.tigo/proxyondemand/", name = "proxyondemand")
@XmlSeeAlso({ObjectFactory.class})
public interface Proxyondemand {

    @WebMethod(operationName = "Ondemand", action = "http://bo.com.tigo/proxyondemand/Ondemand")
    @RequestWrapper(localName = "Ondemand", targetNamespace = "http://bo.com.tigo/proxyondemand/", className = "tigo.com.bo.proxyondemand.Ondemand")
    @ResponseWrapper(localName = "OndemandResponse", targetNamespace = "http://bo.com.tigo/proxyondemand/", className = "tigo.com.bo.proxyondemand.OndemandResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String ondemand(

        @WebParam(name = "msisdn", targetNamespace = "")
        java.lang.String msisdn,
        @WebParam(name = "codigo", targetNamespace = "")
        java.lang.String codigo
    );
}
