package tigo.com.bo.proxyondemand;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-09-13T17:23:50.415-04:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "proxyondemand",
                  wsdlLocation = "file:/C:/Users/Disp-User/Desktop/BELEN/COMMIT/SoapExample/src/main/resources/wsdl/test.wsdl",
                  targetNamespace = "http://bo.com.tigo/proxyondemand/")
public class Proxyondemand_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bo.com.tigo/proxyondemand/", "proxyondemand");
    public final static QName ProxyondemandSOAP = new QName("http://bo.com.tigo/proxyondemand/", "proxyondemandSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Disp-User/Desktop/BELEN/COMMIT/SoapExample/src/main/resources/wsdl/test.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Proxyondemand_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Disp-User/Desktop/BELEN/COMMIT/SoapExample/src/main/resources/wsdl/test.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Proxyondemand_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Proxyondemand_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Proxyondemand_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Proxyondemand_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Proxyondemand_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Proxyondemand_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Proxyondemand
     */
    @WebEndpoint(name = "proxyondemandSOAP")
    public Proxyondemand getProxyondemandSOAP() {
        return super.getPort(ProxyondemandSOAP, Proxyondemand.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Proxyondemand
     */
    @WebEndpoint(name = "proxyondemandSOAP")
    public Proxyondemand getProxyondemandSOAP(WebServiceFeature... features) {
        return super.getPort(ProxyondemandSOAP, Proxyondemand.class, features);
    }

}
